config/routes.rb
Rails.application.routes.draw do
  resources :schedules
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/schedule.rb
class Schedule < ApplicationRecord

enum allday: { "●": 0, present?: 1 }    

validates :title, presence: { message:"を入れてください"}
validates :start, presence: { message:"を入力してください"}
validates :finish, presence: { message:"を入力してください"}



validate :finish_past

def finish_past
    if finish.present? && finish < Date.today
      errors.add(:finish, "は今日以降の日付で選択してください" )
      
    end
end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/schedules_controller.rb
class SchedulesController < ApplicationController
  before_action :set_schedule, only: %i[ show edit update destroy ]


  # GET /schedules or /schedules.json
  def index
    @schedules = Schedule.all
  end

  # GET /schedules/1 or /schedules/1.json
  def show
  end

  # GET /schedules/new
  def new
    @schedule = Schedule.new
  end

  # GET /schedules/1/edit
  def edit
  end

  # POST /schedules or /schedules.json
  def create
    @schedule = Schedule.new(schedule_params)

    respond_to do |format|
      if @schedule.save
        format.html { redirect_to "/schedules", notice: "スケジュールを登録しました" }
        format.json { render :show, status: :created, location: @schedule }
      else
        format.html { render :new, status: :unprocessable_entity }
        flash[:alert] = 'スケジュールを登録できませんでした'
        format.json { render json: @schedule.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /schedules/1 or /schedules/1.json
  def update
    respond_to do |format|
      if @schedule.update(schedule_params)
        format.html { redirect_to "/schedules", notice: "スケジュールを更新しました" }
        format.json { render :show, status: :ok, location: @schedule }
      else
        format.html { render :edit, status: :unprocessable_entity }
        flash[:alert] = 'スケジュールを編集できませんでした'
        format.json { render json: @schedule.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /schedules/1 or /schedules/1.json
  def destroy
    @schedule.destroy
    respond_to do |format|
      format.html { redirect_to schedules_url, notice: "スケジュールを削除しました" }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_schedule
      @schedule = Schedule.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def schedule_params
      params.require(:schedule).permit(:title, :start, :finish, :allday, :content)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/schedules_helper.rb
module SchedulesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Ruby on Rails スケジュール管理アプリ</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="top">
    <h1>Ruby on Rails スケジュール管理アプリ</h1> 
    </div> 
    <%= yield %>
  </body>
</html>

app/views/schedules/_form.html.erb
<%= form_with(model: schedule) do |form| %>
  <% if schedule.errors.any? %>
    <div id="error_explanation">
      <h2>スケジュールを登録できませんでした</h2>

      <ul>
        <% schedule.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>





<p class="center_p">スケジュール新規作成</p>

<table>  
  <tr>
    <th><div class="field">
      <%= form.label :タイトル %></th>
    <td><%= form.text_area :title %></div></td>
  </tr>

  <tr>
    <th><div class="field">
      <%= form.label :開始日 %></th>
    <td><%= form.date_field :start %></div></td>
  </tr>    
  
  <tr>
    <th><div class="field">
      <%= form.label :終了日 %></th>
    <td><%= form.date_field :finish %></div></td>
  <tr>
    <th><div class="field">
      <%= form.label :終日 %></th>
    <td><%= form.check_box :allday, {},"●","" %>
      終日の場合はチェックを入れます</div></td>
  <tr>
    <th><div class="field">
      <%= form.label :スケジュールメモ %></th>
    <td><%= form.text_area :content %></div></td>
  </tr>
</table>

<div class="center_d">
  <%= form.submit :スケジュールを登録する %>
  </div>
<% end %>

app/views/schedules/edit.html.erb
<%= render 'form', schedule: @schedule %>

<p class=center_p><%= link_to 'スケジュール一覧に戻る', schedules_path %></p>

app/views/schedules/index.html.erb
<p class="center_p">スケジュール一覧</p>

<p id="notice"><%= notice %></p>
<p id="notice"><%= alert %></p>

<table>
  <thead>
    <tr>
      <th>ID</th>    
      <th>タイトル</th>
      <th>開始日</th>
      <th>終了日</th>
      <th>終日</th>
      <th>スケジュール更新日時</th>
      <th>確認</th>
      <th>編集</th>
      <th>削除</th>
      
    </tr>
  </thead>

  <tbody>
    <% @schedules.each do |schedule| %>
      <tr>
        <td><%= schedule.id %></td>
        <td><%= schedule.title %></td>
        <td><%= l schedule.start, format: :short%></td>  
        <td><%= l schedule.finish, format: :short%></td> 
        <td><%= schedule.allday %></td>
        <td><%= l schedule.updated_at, format: :short %></td>
        <td><%= link_to '確認', schedule %></td>
        <td><%= link_to '編集', edit_schedule_path(schedule) %></td>
        <td><%= link_to '削除', schedule, method: :delete, data: { confirm: '本当に削除しますか?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>
<p class="schedulepath"><span class="schedulepath2"><%= link_to 'スケジュール新規登録', new_schedule_path %></span></p>
<div class=footer>
<p class="footer2">現在の日時:<%=  I18n.l Time.now, format: :short %><span class="schedules_count">スケジュール合計：<%= @schedules.count %></span>
</p>
</div>

app/views/schedules/new.html.erb
<%= render 'form', schedule: @schedule %>

<p class=center_p><%= link_to 'スケジュール一覧に戻る', schedules_path %></p>

app/views/schedules/show.html.erb
<p id="notice"><%= notice %></p>

<p class="center_p">スケジュール詳細</p>
<table>
  <tr>
  <th>
    <strong>タイトル:</strong></th>
    <td><%= @schedule.title %></td>
  </th>  
  </tr>

  <tr>
  <th>
    <strong>開始日:</strong></th>
    <td><%= l @schedule.start, format: :short %></td>
  </th>  
  </tr>

  <tr>
  <th>
    <strong>投稿日時:</strong></th>
    <td><%= l @schedule.updated_at, format: :short  %></td>
  </th>  
  </tr>

  <tr>
  <th>
    <strong>終日:</strong></th>
    <td><%= @schedule.allday %></td>
  </th>  
  </tr>
  <tr>
  <th>
    <strong>スケジュールメモ:</strong></th>
    <td><%= @schedule.content %></td>
  </th>  
  </tr>
</table>

<div class="center_d">
<%= link_to 'スケジュール一覧に戻る', schedules_path %><br>
<%= link_to 'スケジュールを編集する', edit_schedule_path(@schedule) %> <br>
<%= link_to 'スケジュールを削除', @schedule, method: :delete, data: { confirm: '本当に削除しますか?' } %>
</div>